### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by piacenti** [springfox/springfox-grails-demo#1]
I'm getting this when I run "grailsw run-app"
[error.txt](https://github.com/springfox/springfox-grails-demo/files/1066101/error.txt)

**Comment by dilipkrish** [comment]
Seems like the error is unrelated to this library. 

> Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

**Comment by piacenti** [comment]
I'll try with a different version of grails, this error was with its the latest version with no modifications made to the source code.

**Comment by piacenti** [comment]
Tried with different versions but keep getting the same error. Not sure what hibernate is doing.
